#!/bin/bash

deal(){
  # 判断格式然后使用subfinder处理变动的文件
  subfinder "$1" -c /config/subfinder.json
}

path=/media
exclude=$EXCLUDE
if [ -z $exclude ]; then exclude="None(Use this string to avoid parameter error)"; fi
echo "排除监控条件："$exclude
echo "开始监听"
inotifywait -mr --exclude "$exclude" --timefmt '%Y-%m-%d %H:%M' --format '%w%f' -e create,modify $path |
  while read events; do
    echo $events
    deal "$events"
  done
